version: 0.0.1.{build}-test

os:
- Windows Server 2012 R2

shallow_clone: true

environment:
  LUAROCKS_VER: 2.2.1

  matrix:
    - LUA_VER: 5.1.5
    # - LUA_VER: 5.2.4
    # - LUA_VER: 5.3.0
    # - LJ_VER: 2.0.3
    # - LJ_VER: 2.1

platform:
  - x64
  # - x86

cache:
  - c:\lua -> appveyor.yml
  - c:\com0com
  - c:\external -> appveyor.yml
  - C:\Program Files\LuaRocks -> appveyor.yml
  - C:\Program Files (x86)\LuaRocks -> appveyor.yml

init:
  - call "C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\vcvarsall.bat" %platform%

install:
  # Setup Lua development/build environment
  - call .appveyor\install.bat

before_build:
  # external deps

build_script:
  - luarocks make rockspecs/rs232-scm-0.rockspec

before_test:
  # test deps
  - call .appveyor\install_com0com.bat
  - luarocks install lzmq-timer
  - luarocks install lunitx

test_script:
  - echo "Testing..."
  - cd bindings\lua\test
  - call test_app.bat

after_test:
  # - cd %APPVEYOR_BUILD_FOLDER%
  # - .appveyor\pack_artifact.bat lua-curl bin-rock
